SLING-11727 Fixed Flaky Tests
apache/sling-org-apache-sling-servlets-get pull request #9
Opened 2022-12-11 11:00 UTC by priyanka-28

Descriptions of the changes in this PR:

The tests JsonRendererTest#testBooleansNoTidy and JsonRendererTest#testBooleansNoTidy#testBooleansWithTidy  express non-deterministic behaviour and change the order of the attributes. The fix is adding the JSONAssert to check whether the json objects are equal to ensure determinism.

Motivation
Fixing non-deterministic flaky tests.

2022-12-11 11:59 UTC, kwin commented
The build fails due to usage of undeclared JSON assert library. Maybe there is an approach which doesn’t require adding a new dependency….

2022-12-11 12:01 UTC, kwin commented
https://cassiomolin.com/2019/08/08/comparing-json-documents-in-java-with-jsonp/ seems like a good option

2022-12-14 04:27 UTC, priyanka-28 commented
> https://cassiomolin.com/2019/08/08/comparing-json-documents-in-java-with-jsonp/ seems like a good option

Thank you so much! I have updated the PR with these changes

2022-12-15 07:29 UTC, priyanka-28 commented
> https://cassiomolin.com/2019/08/08/comparing-json-documents-in-java-with-jsonp/ seems like a good option

@kwin are we good to merge these changes?

2022-12-15 07:34 UTC, kwin requested changes
Looks good to me now, apart from the minor nits in the comments.

2022-12-15 07:34 UTC, kwin commented on src/test/java/org/apache/sling/servlets/get/impl/helpers/JsonRendererTest.java
> +        JsonReader jsonReader = Json.createReader(new StringReader(expected));
please use try with resources here.

2022-12-15 07:34 UTC, kwin commented on src/test/java/org/apache/sling/servlets/get/impl/helpers/JsonRendererTest.java
> +        jsonReader = Json.createReader(new StringReader(getJsonFromRequestResponse()));
same as above

2022-12-15 07:34 UTC, kwin commented on src/test/java/org/apache/sling/servlets/get/impl/helpers/JsonRendererTest.java
> +        JsonReader jsonReader = Json.createReader(new StringReader(expected));
same as above

2022-12-15 07:34 UTC, kwin commented on src/test/java/org/apache/sling/servlets/get/impl/helpers/JsonRendererTest.java
> +        jsonReader = Json.createReader(new StringReader(getJsonFromRequestResponse()));
same as above

2022-12-15 09:28 UTC, kwin commented on src/test/java/org/apache/sling/servlets/get/impl/helpers/JsonRendererTest.java
> +        JsonReader jsonReader = Json.createReader(new StringReader(expected));
@priyanka-28 You misunderstood, try with resources calls close automatically, see here for the syntax: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html. No need to catch any exceptions!

2022-12-15 10:56 UTC, priyanka-28 commented
> Looks good to me now, apart from the minor nits in the comments.

@kwin Updated PR!

2022-12-15 11:09 UTC, kwin commented
@priyanka-28 See https://github.com/apache/sling-org-apache-sling-servlets-get/pull/9#discussion_r1049404053

2022-12-15 19:43 UTC, priyanka-28 commented
> @priyanka-28 See [#9 (comment)](https://github.com/apache/sling-org-apache-sling-servlets-get/pull/9#discussion_r1049404053)

@kwin Thank you! Added the try-with-resources block

2022-12-15 21:16 UTC, merged